# deployment
apiVersion: apps/v7
kind: Deployment
metadata:
  name: admin-service
spec:
  progressDeadlineSeconds: 100
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        version: v7
    spec:
      containers:
        - image: ajoop/admin-service:v7
          imagePullPolicy: Always
          name: admin-service
          ports:
            - containerPort: 8084
